In [1]:
import pandas as pd

df = pd.read_csv("superstore_sales_cleaned.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [2]:
numeric_features = df.select_dtypes(include=['int64', 'float64']).columns
categorical_features = df.select_dtypes(include=['object']).columns

print("Numerical Features:")
print(numeric_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
Index(['Row ID', 'Postal Code', 'Sales'], dtype='object')

Categorical Features:
Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')

In [4]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [5]:
df['Sales Per Quantity'] = df['Sales'] / df['Quantity']

KeyError: 'Quantity'

In [6]:
df['Order Year'] = df['Order Date'].dt.year

In [7]:
df[['Order Date', 'Shipping Days', 'Order Year']].head()

  Order Date  Shipping Days  Order Year
0 2017-11-08              3        2017
1 2017-11-08              3        2017
2 2017-06-12              4        2017
3 2016-10-11              7        2016
4 2016-10-11              7        2016

In [8]:
df['Category'].value_counts()

Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64

In [9]:
df = pd.get_dummies(df, columns=['Category'], dtype=int)

In [10]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Sub-Category,Product Name,Sales,Shipping Days,Order Year,Category_Furniture,Category_Office Supplies,Category_Technology
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,2017,1,0,0
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,2017,1,0,0
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,2017,0,1,0
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,2016,1,0,0
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,2016,0,1,0

In [11]:
categorical_to_encode = [
    'Ship Mode',
    'Segment',
    'Region',
    'Sub-Category'
]

df = pd.get_dummies(
    df,
    columns=categorical_to_encode,
    dtype=int
)

In [14]:
df.shape

(9800, 46)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['Sales', 'Shipping Days']] = scaler.fit_transform(
    df[['Sales', 'Shipping Days']]
)

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
pip install scikit-learn