# Day 22 — Feature Encoding

## ABTalks 60-Day Data Science Challenge

Convert categorical variables into numerical representations using Label Encoding and One-Hot Encoding.

In [1]:
import pandas as pd

data = {
    "Age": [22, 35, 28, 42, 31, 25, 38, 29, 45, 33],
    "Gender": ["Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"],
    "City": ["Bangalore", "Mumbai", "Delhi", "Bangalore", "Mumbai",
             "Delhi", "Bangalore", "Mumbai", "Delhi", "Bangalore"],
    "Payment_Method": ["UPI", "Card", "Cash", "UPI", "Card",
                       "Cash", "UPI", "Card", "Cash", "UPI"],
    "Purchase_Amount": [1200, 2500, 800, 3200, 1800,
                        950, 2100, 2700, 1100, 3000],
    "Purchased": [1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
}

df = pd.DataFrame(data)

df

   Age  Gender       City Payment_Method  Purchase_Amount  Purchased
0   22  Female  Bangalore            UPI             1200          1
1   35    Male     Mumbai           Card             2500          1
2   28  Female      Delhi           Cash              800          0
3   42    Male  Bangalore            UPI             3200          1
4   31  Female     Mumbai           Card             1800          1
5   25    Male      Delhi           Cash              950          0
6   38  Female  Bangalore            UPI             2100          1
7   29    Male     Mumbai           Card             2700          1
8   45  Female      Delhi           Cash             1100          0
9   33    Male  Bangalore            UPI             3000          1

In [2]:
# Identify categorical columns
categorical_columns = df.select_dtypes(include="object").columns

print("Categorical columns:")
print(categorical_columns.tolist())

Categorical columns:
['Gender', 'City', 'Payment_Method']

In [3]:
print("Dataset shape before encoding:", df.shape)

print("\nData types:")
print(df.dtypes)

Dataset shape before encoding: (10, 6)

Data types:
Age                 int64
Gender             object
City               object
Payment_Method     object
Purchase_Amount     int64
Purchased           int64
dtype: object

In [4]:
from sklearn.preprocessing import LabelEncoder

df_label = df.copy()

label_encoder = LabelEncoder()

df_label["Gender"] = label_encoder.fit_transform(df_label["Gender"])

df_label

   Age  Gender       City Payment_Method  Purchase_Amount  Purchased
0   22       0  Bangalore            UPI             1200          1
1   35       1     Mumbai           Card             2500          1
2   28       0      Delhi           Cash              800          0
3   42       1  Bangalore            UPI             3200          1
4   31       0     Mumbai           Card             1800          1
5   25       1      Delhi           Cash              950          0
6   38       0  Bangalore            UPI             2100          1
7   29       1     Mumbai           Card             2700          1
8   45       0      Delhi           Cash             1100          0
9   33       1  Bangalore            UPI             3000          1

In [5]:
df_onehot = pd.get_dummies(
    df,
    columns=["City", "Payment_Method"],
    dtype=int
)

df_onehot

,Age,Gender,Purchase_Amount,Purchased,City_Bangalore,City_Delhi,City_Mumbai,Payment_Method_Card,Payment_Method_Cash,Payment_Method_UPI
0,22,Female,1200,1,1,0,0,0,0,1
1,35,Male,2500,1,0,0,1,1,0,0
2,28,Female,800,0,0,1,0,0,1,0
3,42,Male,3200,1,1,0,0,0,0,1
4,31,Female,1800,1,0,0,1,1,0,0
5,25,Male,950,0,0,1,0,0,1,0
6,38,Female,2100,1,1,0,0,0,0,1
7,29,Male,2700,1,0,0,1,1,0,0
8,45,Female,1100,0,0,1,0,0,1,0
9,33,Male,3000,1,1,0,0,0,0,1

In [6]:
print("Before encoding:", df.shape)
print("After one-hot encoding:", df_onehot.shape)

print("\nNew columns:")
print(df_onehot.columns.tolist())

Before encoding: (10, 6)
After one-hot encoding: (10, 10)

New columns:
['Age', 'Gender', 'Purchase_Amount', 'Purchased', 'City_Bangalore', 'City_Delhi', 'City_Mumbai', 'Payment_Method_Card', 'Payment_Method_Cash', 'Payment_Method_UPI']

In [7]:
# Encode all categorical features
df_encoded = pd.get_dummies(
    df,
    columns=["Gender", "City", "Payment_Method"],
    dtype=int
)

# Separate features and target
X = df_encoded.drop("Purchased", axis=1)
y = df_encoded["Purchased"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X.head()

X shape: (10, 10)
y shape: (10,)

,Age,Purchase_Amount,Gender_Female,Gender_Male,City_Bangalore,City_Delhi,City_Mumbai,Payment_Method_Card,Payment_Method_Cash,Payment_Method_UPI
0,22,1200,1,0,1,0,0,0,0,1
1,35,2500,0,1,0,0,1,1,0,0
2,28,800,1,0,0,1,0,0,1,0
3,42,3200,0,1,1,0,0,0,0,1
4,31,1800,1,0,0,0,1,1,0,0

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train baseline model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)

print("Baseline Accuracy:", round(accuracy, 4))

Baseline Accuracy: 0.5

In [9]:
print("Actual:", y_test.tolist())
print("Predicted:", y_pred.tolist())

Actual: [0, 1]
Predicted: [1, 1]

In [10]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 100

df = pd.DataFrame({
    "Age": np.random.randint(18, 60, n),
    "Gender": np.random.choice(["Female", "Male"], n),
    "City": np.random.choice(["Bangalore", "Mumbai", "Delhi"], n),
    "Payment_Method": np.random.choice(["UPI", "Card", "Cash"], n),
    "Purchase_Amount": np.random.randint(500, 5000, n)
})

# Create a simple purchase pattern
df["Purchased"] = (
    (df["Purchase_Amount"] > 2000) |
    (df["Age"] < 25)
).astype(int)

df.head()

   Age  Gender       City Payment_Method  Purchase_Amount  Purchased
0   56  Female     Mumbai            UPI             3450          1
1   46    Male  Bangalore           Cash             4631          1
2   32    Male  Bangalore            UPI             4615          1
3   25    Male      Delhi            UPI             2868          1
4   38  Female     Mumbai           Card             4347          1

In [11]:
from sklearn.preprocessing import LabelEncoder

df_label = df.copy()

for column in ["Gender", "City", "Payment_Method"]:
    encoder = LabelEncoder()
    df_label[column] = encoder.fit_transform(df_label[column])

print("Label Encoded Dataset Shape:", df_label.shape)

df_label.head()

Label Encoded Dataset Shape: (100, 6)

   Age  Gender  City  Payment_Method  Purchase_Amount  Purchased
0   56       0     2               2             3450          1
1   46       1     0               1             4631          1
2   32       1     0               2             4615          1
3   25       1     1               2             2868          1
4   38       0     2               0             4347          1

In [12]:
df_onehot = pd.get_dummies(
    df,
    columns=["Gender", "City", "Payment_Method"],
    dtype=int
)

print("One-Hot Encoded Dataset Shape:", df_onehot.shape)

df_onehot.head()

One-Hot Encoded Dataset Shape: (100, 11)

,Age,Purchase_Amount,Purchased,Gender_Female,Gender_Male,City_Bangalore,City_Delhi,City_Mumbai,Payment_Method_Card,Payment_Method_Cash,Payment_Method_UPI
0,56,3450,1,1,0,0,0,1,0,0,1
1,46,4631,1,0,1,1,0,0,0,1,0
2,32,4615,1,0,1,1,0,0,0,0,1
3,25,2868,1,0,1,0,1,0,0,0,1
4,38,4347,1,1,0,0,0,1,1,0,0

In [13]:
print("Original dataset:", df.shape)
print("Label encoded:", df_label.shape)
print("One-Hot encoded:", df_onehot.shape)

Original dataset: (100, 6)
Label encoded: (100, 6)
One-Hot encoded: (100, 11)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Label Encoding
X_label = df_label.drop("Purchased", axis=1)
y_label = df_label["Purchased"]

X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_label, y_label, test_size=0.2, random_state=42, stratify=y_label
)

label_model = LogisticRegression(max_iter=1000)
label_model.fit(X_train_l, y_train_l)

label_pred = label_model.predict(X_test_l)
label_accuracy = accuracy_score(y_test_l, label_pred)


# One-Hot Encoding
X_onehot = df_onehot.drop("Purchased", axis=1)
y_onehot = df_onehot["Purchased"]

X_train_o, X_test_o, y_train_o, y_test_o = train_test_split(
    X_onehot, y_onehot, test_size=0.2, random_state=42, stratify=y_onehot
)

onehot_model = LogisticRegression(max_iter=1000)
onehot_model.fit(X_train_o, y_train_o)

onehot_pred = onehot_model.predict(X_test_o)
onehot_accuracy = accuracy_score(y_test_o, onehot_pred)


print("Label Encoding Accuracy:", round(label_accuracy, 4))
print("One-Hot Encoding Accuracy:", round(onehot_accuracy, 4))

Label Encoding Accuracy: 0.95
One-Hot Encoding Accuracy: 0.95

In [15]:
performance = pd.DataFrame({
    "Encoding Method": ["Label Encoding", "One-Hot Encoding"],
    "Accuracy": [label_accuracy, onehot_accuracy]
})

performance

    Encoding Method  Accuracy
0    Label Encoding      0.95
1  One-Hot Encoding      0.95

In [16]:
performance.to_csv("day22_encoding_performance.csv", index=False)

print("Performance report saved successfully!")

Performance report saved successfully!

In [17]:
df_label.to_csv("day22_label_encoded_dataset.csv", index=False)

df_onehot.to_csv("day22_onehot_encoded_dataset.csv", index=False)

print("Both encoded datasets saved successfully!")

Both encoded datasets saved successfully!

In [18]:
print("Original Dataset Shape:", df.shape)
print("Label Encoded Shape:", df_label.shape)
print("One-Hot Encoded Shape:", df_onehot.shape)

print("\nPerformance Comparison:")
print(performance)

print("\nDay 22 files created:")
print("✓ day22_label_encoded_dataset.csv")
print("✓ day22_onehot_encoded_dataset.csv")
print("✓ day22_encoding_performance.csv")

Original Dataset Shape: (100, 6)
Label Encoded Shape: (100, 6)
One-Hot Encoded Shape: (100, 11)

Performance Comparison:
    Encoding Method  Accuracy
0    Label Encoding      0.95
1  One-Hot Encoding      0.95

Day 22 files created:
✓ day22_label_encoded_dataset.csv
✓ day22_onehot_encoded_dataset.csv
✓ day22_encoding_performance.csv